### ISSUE TITLE
Add `post-cancellation` event into dropdown list

### ISSUE THREAD

**Issue by teimuraz** [KenkouGmbH/servicebot-gcp-pub-sub#6]

**Comment by rcarcasses** [comment]
We already have it but with a different name `Post decommission` see: 

`https://github.com/KenkouGmbH/servicebot-gcp-pub-sub/blob/7176f890f1ffe02f73a5f50c8810c2d302a6682e/plugins/gcp-pub-subs/view/form.jsx#L119`
